server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: myuser
    password: mysecretpassword
    url: jdbc:postgresql://localhost:5432/clientservice
  flyway:
    enabled: true
    schemas:
      - 'client_service'